/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LastChangeDefinition;
import io.swagger.client.model.MemberDefinition;
import io.swagger.client.model.WorkspaceVuQuotaDefinition;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * FullWorkspaceDefinition
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-16T09:41:51.665+02:00[Europe/Paris]")


public class FullWorkspaceDefinition {
  @SerializedName("allUsersEnabled")
  private Boolean allUsersEnabled = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastChange")
  private LastChangeDefinition lastChange = null;

  @SerializedName("members")
  private List<MemberDefinition> members = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("vuQuota")
  private WorkspaceVuQuotaDefinition vuQuota = null;

  public FullWorkspaceDefinition allUsersEnabled(Boolean allUsersEnabled) {
    this.allUsersEnabled = allUsersEnabled;
    return this;
  }

   /**
   * True if all users of the Workspace are enabled
   * @return allUsersEnabled
  **/
  @Schema(description = "True if all users of the Workspace are enabled")
  public Boolean isAllUsersEnabled() {
    return allUsersEnabled;
  }

  public void setAllUsersEnabled(Boolean allUsersEnabled) {
    this.allUsersEnabled = allUsersEnabled;
  }

  public FullWorkspaceDefinition description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the Workspace
   * @return description
  **/
  @Schema(example = "Workspace description", description = "Description of the Workspace")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FullWorkspaceDefinition id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the Workspace
   * @return id
  **/
  @Schema(example = "5e3acde2e860a132744ca916", description = "Unique identifier of the Workspace")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public FullWorkspaceDefinition lastChange(LastChangeDefinition lastChange) {
    this.lastChange = lastChange;
    return this;
  }

   /**
   * Get lastChange
   * @return lastChange
  **/
  @Schema(description = "")
  public LastChangeDefinition getLastChange() {
    return lastChange;
  }

  public void setLastChange(LastChangeDefinition lastChange) {
    this.lastChange = lastChange;
  }

  public FullWorkspaceDefinition members(List<MemberDefinition> members) {
    this.members = members;
    return this;
  }

  public FullWorkspaceDefinition addMembersItem(MemberDefinition membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<MemberDefinition>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Members assigned to Workspace
   * @return members
  **/
  @Schema(description = "Members assigned to Workspace")
  public List<MemberDefinition> getMembers() {
    return members;
  }

  public void setMembers(List<MemberDefinition> members) {
    this.members = members;
  }

  public FullWorkspaceDefinition name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the Workspace
   * @return name
  **/
  @Schema(example = "Default Workspace", description = "Name of the Workspace")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FullWorkspaceDefinition vuQuota(WorkspaceVuQuotaDefinition vuQuota) {
    this.vuQuota = vuQuota;
    return this;
  }

   /**
   * Get vuQuota
   * @return vuQuota
  **/
  @Schema(description = "")
  public WorkspaceVuQuotaDefinition getVuQuota() {
    return vuQuota;
  }

  public void setVuQuota(WorkspaceVuQuotaDefinition vuQuota) {
    this.vuQuota = vuQuota;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullWorkspaceDefinition fullWorkspaceDefinition = (FullWorkspaceDefinition) o;
    return Objects.equals(this.allUsersEnabled, fullWorkspaceDefinition.allUsersEnabled) &&
        Objects.equals(this.description, fullWorkspaceDefinition.description) &&
        Objects.equals(this.id, fullWorkspaceDefinition.id) &&
        Objects.equals(this.lastChange, fullWorkspaceDefinition.lastChange) &&
        Objects.equals(this.members, fullWorkspaceDefinition.members) &&
        Objects.equals(this.name, fullWorkspaceDefinition.name) &&
        Objects.equals(this.vuQuota, fullWorkspaceDefinition.vuQuota);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allUsersEnabled, description, id, lastChange, members, name, vuQuota);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullWorkspaceDefinition {\n");
    
    sb.append("    allUsersEnabled: ").append(toIndentedString(allUsersEnabled)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastChange: ").append(toIndentedString(lastChange)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vuQuota: ").append(toIndentedString(vuQuota)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
