/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.RateLimitError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdministrationOfUsersApi
 */
@Ignore
public class AdministrationOfUsersApiTest {

    private final AdministrationOfUsersApi api = new AdministrationOfUsersApi();

    /**
     * Delete a user
     *
     * Delete a user with the specified login
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void delete1Test() throws ApiException {
        String login = null;
        Boolean removeFromNeotysSaaSAccount = null;
        api.delete1(login, removeFromNeotysSaaSAccount);

        // TODO: test validations
    }
}
