/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ArrayOfReservationDefinition;
import io.swagger.client.model.ArrayOfZoneDefinition;
import io.swagger.client.model.Error;
import io.swagger.client.model.RateLimitError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesApi
 */
@Ignore
public class ResourcesApiTest {

    private final ResourcesApi api = new ResourcesApi();

    /**
     * Lists reservations
     *
     * Lists the reservations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReservationsTest() throws ApiException {
        String fromDateTime = null;
        String toDateTime = null;
        Integer limit = null;
        Integer offset = null;
        ArrayOfReservationDefinition response = api.getReservations(fromDateTime, toDateTime, limit, offset);

        // TODO: test validations
    }
    /**
     * List all zones
     *
     * Lists the zones.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getZonesTest() throws ApiException {
        ArrayOfZoneDefinition response = api.getZones();

        // TODO: test validations
    }
}
