/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import java.io.File;
import io.swagger.client.model.ProjectDefinition;
import io.swagger.client.model.RateLimitError;
import io.swagger.client.model.RunTestDefinition;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RuntimeApi
 */
@Ignore
public class RuntimeApiTest {

    private final RuntimeApi api = new RuntimeApi();

    /**
     * Runs a test
     *
     * Runs a test of the Account according to the method parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTestsRunTest() throws ApiException {
        String name = null;
        String projectId = null;
        String scenarioName = null;
        String description = null;
        String asCode = null;
        String reservationId = null;
        Long reservationDuration = null;
        Integer reservationWebVUs = null;
        Integer reservationSAPVUs = null;
        String controllerZoneId = null;
        String lgZones = null;
        RunTestDefinition response = api.getTestsRun(name, projectId, scenarioName, description, asCode, reservationId, reservationDuration, reservationWebVUs, reservationSAPVUs, controllerZoneId, lgZones);

        // TODO: test validations
    }
    /**
     * Uploads a NeoLoad project zip file or a standalone as code file
     *
     * Uploads a NeoLoad project of the account corresponding to the parameters. The maximum size file is 100 MB
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postUploadProjectTest() throws ApiException {
        File file = null;
        ProjectDefinition response = api.postUploadProject(file);

        // TODO: test validations
    }
}
