/*
 * NeoLoad API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.ConfigurationTest;
import io.swagger.client.model.WorkspaceDefinitionList;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

import org.junit.Ignore;

/**
 * API tests for WorkspacesApi
 */
@Ignore
public class WorkspacesApiTest {

    private final WorkspacesApi api = new WorkspacesApi();

    static {
    	ConfigurationTest.initTestApiClient();
    }
    
    /**
     * Get the list workspaces that can be accessed
     *
     * The list of all workspaces that can be accessed
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkspaceListTest() throws ApiException {
        WorkspaceDefinitionList response = api.getWorkspaceList();

        assertNotNull(response);
        System.out.println(response.toString());
    }
}
